manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/MarvFPV
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: bt_dis
      import: app/west.yml
  self:
    path: config
