on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (FeO_Earth)
        run: west build -s zmk/app -b FeO_Earth -- -DZMK_CONFIG="${GITHUB_WORKSPACE}"
      - name: FeO_Earth DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/FeO_Earth.dts.pre.tmp
      - name: Feo_Earth Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 FeO_Earth.uf2
      - name: Archive (FeO_Earth)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: FeO_Earth.uf2
